version: '3.7'

services:
  frontend:    
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - '4000:3000'
    depends_on:
      - backend
  backend:
    build: 
      dockerfile: Dockerfile 
      context: ./backend
    ports:
      - '8080:80'
    depends_on:
      - mysql-db
  mysql-db:
    build: 
      dockerfile: Dockerfile
      context: ./mysql-db
    ports: 
      - '3306:3306'