version: '3.7'
services:
  frontend:
    image: frontend
    ports: 
      - '4000:3000'
    depends_on:
      - backend
  backend:
    image: backend
    ports: 
      - '8080:80'
    depends_on:
      - mysql-db   
  mysql-db:
    image: mysql
    ports: 
      - '3306:3306'      

      

