version: '3.7'
volumes: 
  mysql-db-data:
    name: mysql-db-data
services:
  frontend:    
    build: 
      dockerfile: Dockerfile
      context: ./frontend      
    environment: 
      - HOST_API=backend #IP PARA CONSUMIR LA API
      #- PORT_API=3000        #PUERTO DE API      
      #- PORT=80
    ports:
      - '80:80'  
    depends_on:
      - backend
  backend:
    build: 
      dockerfile: Dockerfile 
      context: ./backend
    environment: 
      - HOST=mysql-db #IP DE LA BASE DE DATOS
      #- PORT=3000          #PUERTO DONDE CORREO EL BACKEND
    ports:
      - '4000:4000'         #PUERTO DONDE CORRE EL BACKEND
    depends_on:
      - mysql-db
  mysql-db:
    #hostname: db
    build: 
      dockerfile: Dockerfile
      context: ./mysql-db      
    ports: 
      - '3306:3306'
    volumes: 
      - 'mysql-db-data:/var/lib/mysql'